import type { Config } from 'tailwindcss'

// Design tokens ported from docs/design/DESIGN.md ("Modern Bistro Heritage")
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f8',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#5d3f3b',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#926f69',
        'outline-variant': '#e7bdb6',
        'surface-tint': '#c00000',
        primary: '#970000',
        'on-primary': '#ffffff',
        'primary-container': '#c40000',
        'on-primary-container': '#ffd1ca',
        'inverse-primary': '#ffb4a8',
        secondary: '#635d5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e9e0e1',
        'on-secondary-container': '#696364',
        tertiary: '#474948',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5f6160',
        'on-tertiary-container': '#dcdcda',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary-fixed': '#410000',
        'on-primary-fixed-variant': '#930000',
        'secondary-fixed': '#e9e0e1',
        'secondary-fixed-dim': '#cdc4c5',
        'on-secondary-fixed': '#1e1b1c',
        'on-secondary-fixed-variant': '#4b4546',
        'tertiary-fixed': '#e2e3e1',
        'tertiary-fixed-dim': '#c6c7c5',
        'on-tertiary-fixed': '#1a1c1b',
        'on-tertiary-fixed-variant': '#454746',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e2',
      },
      fontFamily: {
        heading: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        touch: '48px',
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
} satisfies Config
